export const GET_LOCAL_USER_PROFILE = "GET_LOCAL_USER_PROFILE";
export const GET_LOCAL_USER_ROLES = "GET_LOCAL_USER_ROLES";
export const GET_LOCAL_ROLE = "GET_LOCAL_ROLE";
export const GET_LOCAL_PERMISSION = "GET_LOCAL_PERMISSION";
export const GET_LOCAL_ROLE_PERMISSION = "GET_LOCAL_ROLE_PERMISSION";
export const GET_LOCAL_USER_LIST = "GET_LOCAL_USER_LIST";
export const GET_LOCAL_ROLE_GROUPS = "GET_LOCAL_ROLE_GROUPS";
export const GET_MEDIA_FOLDERS = "GET_MEDIA_FOLDERS";
export const GET_MEDIA_FILES = "GET_MEDIA_FILES";

export const queryCore = {
    GET_LIST_REGION: "GET_LIST_REGION",
    GET_INVENTORY_TYPE_LIST: "GET_INVENTORY_TYPE_LIST",
    GET_PRODUCT_TYPE_LIST: "GET_PRODUCT_TYPE_LIST",
    GET_INVENTORY_LIST: "GET_INVENTORY_LIST",
    GET_INVENTORY_DETAIL: "GET_INVENTORY_DETAIL",
    CREATE_INVENTORY_ITEM: "CREATE_INVENTORY_ITEM",
    GET_STOCK_INVENTORY_TYPE: "GET_STOCK_INVENTORY_TYPE",
    GET_STOCK_LIST_INVENTORY: "GET_STOCK_LIST_INVENTORY",
    GET_STOCK_DETAIL_INVENTORY: "GET_STOCK_DETAIL_INVENTORY",
    GET_LIST_TEMPLATE_SELLABLE: "GET_LIST_TEMPLATE_SELLABLE",
    GET_SELLABLE_LIST: "GET_SELLABLE_LIST",
    GET_SELLABLE_PRICE_CONFIGS: "GET_SELLABLE_PRICE_CONFIGS",
    GET_SELLABLE_DETAIL: "GET_SELLABLE_DETAIL",
    GET_BOOKING_ORDER_LIST: "GET_BOOKING_ORDER_LIST",
    GET_BOOKING_ORDER_DETAIL: "GET_BOOKING_ORDER_DETAIL",
    GET_BOOKING_BOOKING_TOUR_SERVIES: "GET_BOOKING_BOOKING_TOUR_SERVIES",
    GET_RULE_POLICY_DEPOSIT_CAT_LIST: "GET_RULE_POLICY_DEPOSIT_CAT_LIST",
    GET_RULE_POLICY_DEPOSIT_RULE_LIST: "GET_RULE_POLICY_DEPOSIT_RULE_LIST",
    GET_RULE_POLICY_LIMIT_TIME_CAT_LIST: "GET_RULE_POLICY_LIMIT_TIME_CAT_LIST",
    GET_RULE_POLICY_LIMIT_TIME_RULE_LIST:
        "GET_RULE_POLICY_LIMIT_TIME_RULE_LIST",

    GET_RULE_POLICY_PENALTY_CAT_LIST: "GET_RULE_POLICY_PENALTY_CAT_LIST",
    GET_RULE_POLICY_PENALTY_RULE_LIST: "GET_RULE_POLICY_PENALTY_RULE_LIST",
    GET_FORM_OF_PAYMENT_LIST: "GET_FORM_OF_PAYMENT_LIST",
};

export const queryMisc = {
    GET_DESTINATION_LIST: "GET_DESTINATION_LIST",
    GET_DESTINATION_DETAIL: "GET_DESTINATION_DETAIL",
};

export const queryCMS = {
    GET_DESTINATION_CMS_LIST: "GET_DESTINATION_CMS_LIST",
    GET_DESTINATION_CMS_DETAIL: "GET_DESTINATION_CMS_DETAIL",
    GET_LOCAL_SEACH_DESTINATION: "GET_LOCAL_SEACH_DESTINATION",
    GET_LOCAL_RULE_AND_POLICY_LIST: "GET_LOCAL_RULE_AND_POLICY_LIST",
    GET_TRANSLATION_LIST_FE: "GET_TRANSLATION_LIST_FE",
    GET_PAGE_LIST: "GET_PAGE_LIST",
};
