export const GET_LOCAL_USER_PROFILE = "GET_LOCAL_USER_PROFILE";
export const GET_LOCAL_USER_ROLES = "GET_LOCAL_USER_ROLES";
export const GET_LOCAL_ROLE = "GET_LOCAL_ROLE";
export const GET_LOCAL_PERMISSION = "GET_LOCAL_PERMISSION";
export const GET_LOCAL_ROLE_PERMISSION = "GET_LOCAL_ROLE_PERMISSION";
export const GET_LOCAL_USER_LIST = "GET_LOCAL_USER_LIST";
export const GET_LOCAL_ROLE_GROUPS = "GET_LOCAL_ROLE_GROUPS";
export const GET_MEDIA_FOLDERS = "GET_MEDIA_FOLDERS";
export const GET_MEDIA_FILES = "GET_MEDIA_FILES";

export const queryCore = {
    GET_LIST_REGION: "GET_LIST_REGION",
    GET_INVENTORY_TYPE_LIST: "GET_INVENTORY_TYPE_LIST",
    GET_PRODUCT_TYPE_LIST: "GET_PRODUCT_TYPE_LIST",
    GET_INVENTORY_LIST: "GET_INVENTORY_LIST",
    GET_INVENTORY_DETAIL: "GET_INVENTORY_DETAIL",
    CREATE_INVENTORY_ITEM: "CREATE_INVENTORY_ITEM",
    GET_STOCK_INVENTORY_TYPE: "GET_STOCK_INVENTORY_TYPE",
    GET_STOCK_LIST_INVENTORY: "GET_STOCK_LIST_INVENTORY",
    GET_STOCK_DETAIL_INVENTORY: "GET_STOCK_DETAIL_INVENTORY",
    GET_LIST_TEMPLATE_SELLABLE: "GET_LIST_TEMPLATE_SELLABLE",
};

export const queryMisc = {
    GET_DESTINATION_LIST: "GET_DESTINATION_LIST",
    GET_DESTINATION_DETAIL: "GET_DESTINATION_DETAIL",
};

export const queryCMS = {
    GET_DESTINATION_CMS_LIST: "GET_DESTINATION_CMS_LIST",
    GET_DESTINATION_CMS_DETAIL: "GET_DESTINATION_CMS_DETAIL",
};
