import {
  IconMeal,
  IconTicketPercent,
  IconBus,
  IconBuilding,
  IconStarOutline,
  IconUtensilOutline,
  IconRecieptText,
  IconCitrus,
  IconCaravan,
  IconCloudMoon,
  IconCookie,
  IconCrown,
  IconFlame,
  IconFlower,
  IconShield,
  IconShieldCheck,
  IconShieldOff,
  IconShieldPlus,
  IconSparklesOutline,
  IconBellRing,
  IconCar,
  IconCheckCircle,
  IconDollarSignCircle,
  IconClock,
  IconCloudSun,
  IconFlagTriangleRight,
  IconHouse,
  IconTag,
  IconTags,
  IconTicket,
  IconHelpCircle,
  IconXCircle,
  IconPartyPopper,
  IconPackageCheck,
  IconBookMark,
  IconBan,
  IconUserCheck,
  IconUsers,
  IconSend,
  IconCalendarDays,
  IconMapPinned,
} from "@/assets/icons";
export const ICON_LIST = [
  {
    name: "Ban",
    key: "IconBan",
    icon: IconBan,
  },
  {
    name: "Bell ring",
    key: "IconBellRing",
    icon: IconBellRing,
  },
  {
    name: "Book mark",
    key: "IconBookMark",
    icon: IconBookMark,
  },
  {
    name: "Bus",
    key: "IconBus",
    icon: IconBus,
  },
  {
    name: "Building",
    key: "IconBuilding",
    icon: IconBuilding,
  },
  {
    name: "Caravan",
    key: "IconCaravan",
    icon: IconCaravan,
  },
  {
    name: "Calendar days",
    key: "IconCalendarDays",
    icon: IconCalendarDays,
  },
  {
    name: "Citrus",
    key: "IconCitrus",
    icon: IconCitrus,
  },

  {
    name: "Cloud moon",
    key: "IconCloudMoon",
    icon: IconCloudMoon,
  },
  {
    name: "Cookie",
    key: "IconCookie",
    icon: IconCookie,
  },
  {
    name: "Crown",
    key: "IconCrown",
    icon: IconCrown,
  },
  {
    name: "Car",
    key: "IconCar",
    icon: IconCar,
  },
  {
    name: "Clock",
    key: "IconClock",
    icon: IconClock,
  },
  {
    name: "Cloud sun",
    key: "IconCloudSun",
    icon: IconCloudSun,
  },

  {
    name: "Check circle",
    key: "IconCheckCircle",
    icon: IconCheckCircle,
  },
  {
    name: "Dollar circle",
    key: "IconDollarSignCircle",
    icon: IconDollarSignCircle,
  },
  {
    name: "Star outline",
    key: "IconStarOutline",
    icon: IconStarOutline,
  },
  {
    name: "Utensil",
    key: "IconUtensilOutline",
    icon: IconUtensilOutline,
  },
  {
    name: "Reciept text",
    key: "IconRecieptText",
    icon: IconRecieptText,
  },
  {
    name: "Flame",
    key: "IconFlame",
    icon: IconFlame,
  },
  {
    name: "Flower",
    key: "IconFlower",
    icon: IconFlower,
  },
  {
    name: "Shield",
    key: "IconShield",
    icon: IconShield,
  },
  {
    name: "Shield check",
    key: "IconShieldCheck",
    icon: IconShieldCheck,
  },
  {
    name: "Shield off",
    key: "IconShieldOff",
    icon: IconShieldOff,
  },
  {
    name: "Shield plus",
    key: "IconShieldPlus",
    icon: IconShieldPlus,
  },
  {
    name: "Sparkles",
    key: "IconSparklesOutline",
    icon: IconSparklesOutline,
  },

  {
    name: "Flag triangle right",
    key: "IconFlagTriangleRight",
    icon: IconFlagTriangleRight,
  },
  {
    name: "House",
    key: "IconHouse",
    icon: IconHouse,
  },
  {
    name: "Meal",
    key: "IconMeal",
    icon: IconMeal,
  },
  {
    name: "Ticket percent",
    key: "IConTicketPercent",
    icon: IconTicketPercent,
  },
  {
    name: "Tag",
    key: "IconTag",
    icon: IconTag,
  },
  {
    name: "Tags",
    key: "IconTags",
    icon: IconTags,
  },
  {
    name: "Ticket",
    key: "IconTicket",
    icon: IconTicket,
  },
  {
    name: "Help Circle",
    key: "IconHelpCircle",
    icon: IconHelpCircle,
  },
  {
    name: "X Circle",
    key: "IconXCircle",
    icon: IconXCircle,
  },
  {
    name: "Party popper",
    key: "IconPartyPopper",
    icon: IconPartyPopper,
  },
  {
    name: "Package check",
    key: "IconPackageCheck",
    icon: IconPackageCheck,
  },

  {
    name: "User check",
    key: "IconUserCheck",
    icon: IconUserCheck,
  },
  {
    name: "Users",
    key: "IconUsers",
    icon: IconUsers,
  },
  {
    name: "Send",
    key: "IconSend",
    icon: IconSend,
  },

  {
    name: "Map pinned",
    key: "IconMapPinned",
    icon: IconMapPinned,
  },
];
