export const LINKS = {
    Home: "/",
    PortalLogin: "/ag/login",
    PortalForgotPassword: "/ag/forgot-password",
    DashBoard: "/portal/dashboard",
    MyAccount: "/portal/my-account",
    DestinationList: "/portal/destination",
    ProductInventoryList: "/portal/product/inventory",
    ProductStockList: "/portal/product/inventory/{inventoryId}",
    ProductStockDetail: "/portal/product/stock/{stockInventoryId}",
    TemplateSellable: "/portal/product/template-sellable",
    Sellable: "/portal/product/template-sellable/{tempalteSellableId}",
    PageCreate: "/portal/contents/page/create",
    CMSTemplateCreate: "/portal/cms-template/create",
    CMSTemplatePageList: "/portal/cms-template/list",
};
