export const LINKS = {
  Home: "/",
  PortalLogin: "/ag/login",
  PortalForgotPassword: "/ag/forgot-password",
  DashBoard: "/portal/dashboard",
  MyAccount: "/portal/my-account",
  DestinationList: "/portal/destination",
  NoticeCreate: "/portal/destination/notice-information/create",
  NoticeList: "/portal/destination/notice-information",
  ProductInventoryList: "/portal/product/inventory",
  ProductStockList: "/portal/product/inventory/{inventoryId}",
  ProductStockDetail: "/portal/product/stock/{stockInventoryId}",
  TemplateSellable: "/portal/product/template-sellable",
  Sellable: "/portal/product/template-sellable/{tempalteSellableId}",
  PageCreate: "/portal/contents/page/create",
  PostCreate: "/portal/contents/post/create",
  CMSTemplateCreate: "/portal/cms-template/create",
  CMSTemplatePageList: "/portal/cms-template/list",
  VisaTemplateList: "/portal/visa-template/list",
  VisaTemplateCreate: "/portal/visa-template/list",
  TagCreate: "/portal/contents/tag/create",
  TagList: "/portal/contents/tag",
  CategoryCreate: "/portal/contents/category/create",
  CategoryList: "/portal/contents/category/list",
};
