export enum ERolesFunctions {
  POST_LIST = "POST_LIST",
  POST_CREATE = "POST_CREATE",
  POST_UPDATE = "POST_UPDATE",
  POST_DELETE = "POST_DELETE",
  CATEGORY_LIST = "CATEGORY_LIST",
  CATEGORY_CREATE = "CATEGORY_CREATE",
  CATEGORY_UPDATE = "CATEGORY_UPDATE",
  CATEGORY_DELETE = "CATEGORY_DELETE",
  TAG_UPDATE = "TAG_UPDATE",
  TAG_CREATE = "TAG_CREATE",
  TAG_LIST = "TAG_LIST",
  TAG_DELETE = "TAG_DELETE",
  COMMENT_UPDATE = "COMMENT_UPDATE",
  COMMENT_CREATE = "COMMENT_CREATE",
  COMMENT_LIST = "COMMENT_LIST",
  COMMENT_DELETE = "COMMENT_DELETE",
  MENU_UPDATE = "MENU_UPDATE",
  MENU_CREATE = "MENU_CREATE",
  MENU_LIST = "MENU_LIST",
  MENU_DELETE = "MENU_DELETE",
  USER_UPDATE = "USER_UPDATE",
  USER_CREATE = "USER_CREATE",
  USER_LIST = "USER_LIST",
  USER_DELETE = "USER_DELETE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_LIST = "ROLE_LIST",
  PERMISSION_UPDATE = "PERMISSION_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",
  PERMISSION_CREATE = "PERMISSION_CREATE",
  PERMISSION_LIST = "PERMISSION_LIST",
  PERMISSION_DELETE = "PERMISSION_DELETE",
  AGENT_UPDATE = "AGENT_UPDATE",
  AGENT_CREATE = "AGENT_CREATE",
  AGENT_LIST = "AGENT_LIST",
  AGENT_DELETE = "AGENT_DELETE",
  MANAGE_BOOKING = "MANAGE_BOOKING",
  MANAGE_BOOKING_LIST = "MANAGE_BOOKING_LIST",
  MANAGE_BOOKING_ADD_ONS = "MANAGE_BOOKING_ADD_ONS",
  MANAGE_BOOKING_SPLIT = "MANAGE_BOOKING_SPLIT",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_LIST = "PRODUCT_LIST",
  PRODUCT_DELETE = "PRODUCT_DELETE",
  MEDIA_UPDATE = "MEDIA_UPDATE",
  MEDIA_CREATE = "MEDIA_CREATE",
  MEDIA_LIST = "MEDIA_LIST",
  MEDIA_DELETE = "MEDIA_DELETE",

  LANGUAGE_UPDATE = "LANGUAGE_UPDATE",
  LANGUAGE_CREATE = "LANGUAGE_CREATE",
  LANGUAGE_LIST = "LANGUAGE_LIST",
  LANGUAGE_DELETE = "LANGUAGE_DELETE",

  REGION_UPDATE = "REGION_UPDATE",
  REGION_CREATE = "REGION_CREATE",
  REGION_LIST = "REGION_LIST",
  REGION_DELETE = "REGION_DELETE",
  DASHBOARD_VIEW = "DASHBOARD_VIEW",

  SYSTEM_MANAGEMENT = "SYSTEM_MANAGEMENT",

  VENDOR_LIST = "VENDOR_LIST",
  VENDOR_CREATE = "VENDOR_CREATE",
  VENDOR_UPDATE = "VENDOR_UPDATE",
  VENDOR_DELETE = "VENDOR_DELETE",
  SUPPLIER_LIST = "SUPPLIER_LIST",
  SUPPLIER_CREATE = "SUPPLIER_CREATE",
  SUPPLIER_UPDATE = "SUPPLIER_UPDATE",
  SUPPLIER_DELETE = "SUPPLIER_DELETE",
  FOP_LIST = "FOP_LIST",
  FOP_CREATE = "FOP_CREATE",
  FOP_UPDATE = "FOP_UPDATE",
  FOP_DELETE = "FOP_DELETE",

  LEADING_LIST = "LEADING_LIST",
  LEADING_CREATE = "LEADING_CREATE",
  LEADING_UPDATE = "LEADING_UPDATE",
  LEADING_DELETE = "LEADING_DELETE",

  DOCUMENT_CHECK_LIST_UPDATE = "DOCUMENT_CHECK_LIST_UPDATE",
  DOCUMENT_CHECK_LIST_CREATE = "DOCUMENT_CHECK_LIST_CREATE",
  DOCUMENT_CHECK_LIST_LIST = "DOCUMENT_CHECK_LIST_LIST",
  DOCUMENT_CHECK_LIST_DELETE = "DOCUMENT_CHECK_LIST_DELETE",

  SELLABLE_UPDATE = "SELLABLE_UPDATE",
  SELLABLE_CREATE = "SELLABLE_CREATE",
  SELLABLE_LIST = "SELLABLE_LIST",
  SELLABLE_DELETE = "SELLABLE_DELETE",

  INVENTORY_UPDATE = "INVENTORY_UPDATE",
  INVENTORY_CREATE = "INVENTORY_CREATE",
  INVENTORY_LIST = "INVENTORY_LIST",
  INVENTORY_DELETE = "INVENTORY_DELETE",

  STOCK_UPDATE = "STOCK_UPDATE",
  STOCK_CREATE = "STOCK_CREATE",
  STOCK_LIST = "STOCK_LIST",
  STOCK_DELETE = "STOCK_DELETE",

  TEMPLATE_UPDATE = "TEMPLATE_UPDATE",
  TEMPLATE_CREATE = "TEMPLATE_CREATE",
  TEMPLATE_LIST = "TEMPLATE_LIST",
  TEMPLATE_DELETE = "TEMPLATE_DELETE",

  TEMPLATE_CONTENT_UPDATE = "TEMPLATE_CONTENT_UPDATE",
  TEMPLATE_CONTENT_CREATE = "TEMPLATE_CONTENT_CREATE",
  TEMPLATE_CONTENT_LIST = "TEMPLATE_CONTENT_LIST",
  TEMPLATE_CONTENT_DELETE = "TEMPLATE_CONTENT_DELETE",

  COUPON_UPDATE = "COUPON_UPDATE",
  COUPON_CREATE = "COUPON_CREATE",
  COUPON_LIST = "COUPON_LIST",
  COUPON_DELETE = "COUPON_DELETE",

  DESTINATION_UPDATE = "DESTINATION_UPDATE",
  DESTINATION_CREATE = "DESTINATION_CREATE",
  DESTINATION_LIST = "DESTINATION_LIST",
  DESTINATION_DELETE = "DESTINATION_DELETE",

  OPERATION = "OPERATION",
  BOOKING_TOUR_CREATE = "BOOKING_TOUR_CREATE",
  BOOKING_MICE_CREATE = "BOOKING_MICE_CREATE",
  BOOKING_SERVICE_CREATE = "BOOKING_SERVICE_CREATE",
}

export type TRoleCondition = (ERolesFunctions | { $or: TRoleCondition })[];

export const roleConfigs = {
  post: {
    list: [ERolesFunctions.POST_LIST],
    add: [ERolesFunctions.POST_CREATE],
    update: [ERolesFunctions.POST_UPDATE],
    delete: [ERolesFunctions.POST_DELETE],
  },
  category: {
    list: [ERolesFunctions.CATEGORY_LIST],
    add: [ERolesFunctions.CATEGORY_CREATE],
    update: [ERolesFunctions.CATEGORY_UPDATE],
    delete: [ERolesFunctions.CATEGORY_DELETE],
  },
  tag: {
    list: [ERolesFunctions.TAG_LIST],
    add: [ERolesFunctions.TAG_CREATE],
    update: [ERolesFunctions.TAG_UPDATE],
    delete: [ERolesFunctions.TAG_DELETE],
  },
  media: {
    list: [ERolesFunctions.MEDIA_LIST],
    add: [ERolesFunctions.MEDIA_CREATE],
    update: [ERolesFunctions.MEDIA_UPDATE],
    delete: [ERolesFunctions.MEDIA_DELETE],
  },
  comment: {
    list: [ERolesFunctions.COMMENT_LIST],
    add: [ERolesFunctions.COMMENT_CREATE],
    update: [ERolesFunctions.COMMENT_UPDATE],
    delete: [ERolesFunctions.COMMENT_DELETE],
  },
  menu: {
    list: [ERolesFunctions.MENU_LIST],
    add: [ERolesFunctions.MENU_CREATE],
    update: [ERolesFunctions.MENU_UPDATE],
    delete: [ERolesFunctions.MENU_DELETE],
  },
  user: {
    list: [ERolesFunctions.USER_LIST],
    leading: [ERolesFunctions.LEADING_LIST],
  },
  role: {
    list: [ERolesFunctions.ROLE_LIST],
    add: [ERolesFunctions.ROLE_CREATE],
    update: [ERolesFunctions.ROLE_UPDATE],
    delete: [ERolesFunctions.ROLE_DELETE],
  },
  permission: {
    list: [ERolesFunctions.PERMISSION_LIST],
    add: [ERolesFunctions.PERMISSION_CREATE],
    update: [ERolesFunctions.PERMISSION_UPDATE],
    delete: [ERolesFunctions.PERMISSION_DELETE],
  },
  agent: {
    list: [ERolesFunctions.AGENT_LIST],
    add: [ERolesFunctions.AGENT_CREATE],
    update: [ERolesFunctions.AGENT_UPDATE],
    delete: [ERolesFunctions.AGENT_DELETE],
  },
  booking: {
    tour: [ERolesFunctions.BOOKING_TOUR_CREATE],
    mice: [ERolesFunctions.BOOKING_MICE_CREATE],
    service: [ERolesFunctions.BOOKING_SERVICE_CREATE],
  },
  manageBooking: {
    list: [ERolesFunctions.MANAGE_BOOKING_LIST],
    fop: { list: [ERolesFunctions.FOP_LIST] },
  },
  product: {
    inventory: { list: [ERolesFunctions.INVENTORY_LIST] },
    destination: {
      list: [ERolesFunctions.DESTINATION_LIST],
    },
    template: { list: [ERolesFunctions.TEMPLATE_LIST] },
    selable: { list: [ERolesFunctions.SELLABLE_LIST] },
    vendor: {
      list: [ERolesFunctions.VENDOR_LIST],
    },
    stock: {
      list: [ERolesFunctions.STOCK_LIST],
    },
    supplier: {
      list: [ERolesFunctions.SUPPLIER_LIST],
    },
    coupon: { list: [ERolesFunctions.COUPON_LIST] },
    templateContent: {
      list: [ERolesFunctions.TEMPLATE_CONTENT_LIST],
    },
  },
  language: {
    list: [ERolesFunctions.LANGUAGE_LIST],
    add: [ERolesFunctions.LANGUAGE_CREATE],
    update: [ERolesFunctions.LANGUAGE_UPDATE],
    delete: [ERolesFunctions.LANGUAGE_DELETE],
  },
  dashboard: {
    view: [ERolesFunctions.DASHBOARD_VIEW],
  },
  systemConfig: {
    management: [ERolesFunctions.SYSTEM_MANAGEMENT],
  },

  operation: {
    list: [ERolesFunctions.OPERATION],
  },
};

export const PATH_WITH_PERMISSION = {
  dashboard: roleConfigs.dashboard.view,
  guide: roleConfigs.dashboard.view,
  booking: roleConfigs.booking.tour,
  "booking-request": roleConfigs.booking.mice,
  "manage-booking": roleConfigs.manageBooking.list,
  "manage-booking/order-list": roleConfigs.manageBooking.list,
  "manage-booking/form-of-payment": roleConfigs.manageBooking.fop.list,
  user: roleConfigs.user.list,
  "role-permission": roleConfigs.role.list,
  role: roleConfigs.role.list,
  menu: roleConfigs.menu.list,
  "menu/primary": roleConfigs.menu.list,
  "menu/secondary": roleConfigs.menu.list,
  "menu/footer": roleConfigs.menu.list,
  "menu/footer-info": roleConfigs.menu.list,
  "menu/mobile": roleConfigs.menu.list,
  product: [
    { $or: roleConfigs.product.inventory.list },
    { $or: roleConfigs.product.selable.list },
    { $or: roleConfigs.product.stock.list },
    { $or: roleConfigs.product.supplier.list },
    { $or: roleConfigs.product.template.list },
    { $or: roleConfigs.product.vendor.list },
  ],
  "product/manage-vendor": roleConfigs.product.vendor.list,
  "product/manage-supplier": roleConfigs.product.supplier.list,
  "product/inventory": roleConfigs.product.inventory.list,
  "product/stock": roleConfigs.product.stock.list,
  "product/template-sellable": roleConfigs.product.template.list,
  "product/sellable": roleConfigs.product.selable.list,
  "content-template": [
    {
      $or: roleConfigs.product.templateContent.list,
    },
  ],
  "content-template/sellable/list": roleConfigs.product.templateContent.list,
  "content-template/misc-document/list": roleConfigs.product.templateContent.list,
  "content-template/misc-depart/list": roleConfigs.product.templateContent.list,
  "content-template/visa/list": roleConfigs.product.templateContent.list,
  leading: roleConfigs.user.leading,
  "leading/list": roleConfigs.user.leading,
  language: roleConfigs.language.list,
  "system-configuration": roleConfigs.systemConfig.management,
  "system-configuration/general": roleConfigs.systemConfig.management,
  "system-configuration/rule-policy": roleConfigs.systemConfig.management,
  "operation/list": roleConfigs.operation.list,
  operation: roleConfigs.operation.list,
  "discount-policy": roleConfigs.product.coupon.list,
  "discount-policy/coupon": roleConfigs.product.coupon.list,
  "discount-policy/policy": roleConfigs.product.coupon.list,
  destination: roleConfigs.product.destination.list,
  "destination/list": roleConfigs.product.destination.list,
  "destination/search-group": roleConfigs.product.destination.list,
  "destination/notice-information": roleConfigs.product.destination.list,
  post: roleConfigs.post.list,
  page: roleConfigs.post.list,
  tag: roleConfigs.tag.list,
  category: roleConfigs.category.list,
  media: roleConfigs.media.list,
};
