const ADMIN_AUTH = {
  GET_ADMIN_PROFILE: "GET_ADMIN_PROFILE",
  GET_ADMIN_ROLES: "GET_ADMIN_ROLES",
} as const;

const ROLES_PERS = {
  ROLES: "GET_ROLES",
  PERMISSIONS: "PERMISSIONS",
  ROLE_PERMISSIONS: "ROLE_PERMISSIONS",
} as const;

const MEDIA_QUERY = {
  GET_MEDIA_FOLDERS: "GET_MEDIA_FOLDERS",
  GET_MEDIA_FILES: "GET_MEDIA_FILES",
} as const;

export { ADMIN_AUTH, ROLES_PERS, MEDIA_QUERY };
