const ADMIN_AUTH = {
  GET_ADMIN_PROFILE: "GET_ADMIN_PROFILE",
  GET_ADMIN_ROLES: "GET_ADMIN_ROLES",
} as const;

const ROLES_PERS = {
  ROLES: "GET_ROLES",
  PERMISSIONS: "PERMISSIONS",
  ROLE_PERMISSIONS: "ROLE_PERMISSIONS",
} as const;

const MEDIA_QUERY = {
  GET_MEDIA_FOLDERS: "GET_MEDIA_FOLDERS",
  GET_MEDIA_FILES: "GET_MEDIA_FILES",
} as const;

const MEMBER_QUERY = {
  GET_MEMBER_LIST: "GET_MEMBER_LIST",
};

const TRANSLATION_QUERY = {
  GET_TRANSLATION_LIST: "GET_TRANSLATION_LIST",
};

export { ADMIN_AUTH, ROLES_PERS, MEDIA_QUERY, MEMBER_QUERY, TRANSLATION_QUERY };
