const ADMIN_AUTH = {
  GET_ADMIN_PROFILE: "GET_ADMIN_PROFILE",
  GET_ADMIN_ROLES: "GET_ADMIN_ROLES",
  GET_ADMIN_PERMISSIONS: "GET_ADMIN_PERMISSIONS",
} as const;

const ROLES_PERS = {
  ROLES: "GET_ROLES",
  PERMISSIONS: "PERMISSIONS",
  ROLE_PERMISSIONS: "ROLE_PERMISSIONS",
} as const;

export { ADMIN_AUTH, ROLES_PERS };
